### ISSUE TITLE
Create plots without DISPLAY variable

### ISSUE THREAD

**Issue by EmanueleGhelfi** [hutec/tensorbot#1]
Hi, 
First of all thanks for your bot, very useful for experiment monitoring. 
I'm using your bot on a server (no DISPLAY variable) and this was causing me an issue while asking the bot to create plots. 
I've added the following line in bot.py:
```
plt.switch_backend('agg')
```
After the line:
```
import matplotlib.pyplot as plt
```
The bot now works as expected and creates plots. I suggest to modify your code adding this line.

Thanks.

**Comment by hutec** [comment]
Hi Emanuele,

First, sorry for the late reply and thank you for your suggestion.
I have added the switch to the agg backend in d6e972c79bd5652c4fab78dba8cd4aff06fa721f.
